In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
clean_data_path = Path("archive\cleaned_ckd.csv")
clean_data = pd.read_csv(clean_data_path)
# Review the DataFrame
print(clean_data.head())
print(clean_data.info()) 

   Unnamed: 0  age  blood_pressure  specific_gravity  albumin  sugar  \
0           0   48              80             1.020      1.0    0.0   
1           1    7              50             1.020      4.0    0.0   
2           2   62              80             1.010      2.0    3.0   
3           3   48              70             1.005      4.0    0.0   
4           4   51              80             1.010      2.0    0.0   

   red_blood_cells  pus_cell  pus_cell_clumps  bacteria  ...  \
0                0         1                1         1  ...   
1                0         1                1         1  ...   
2                1         1                1         1  ...   
3                1         2                2         1  ...   
4                1         1                1         1  ...   

   packed_cell_volume  white_blood_cell_count  red_blood_cell_count  \
0                  44                    7800              5.200000   
1                  38                   

In [3]:
#HELP FROM GROUP, DETERMINE CORRECT VARIABLES

# Separate the data into labels and features

# Separate the y variable, the labels
y = clean_data['age']

# Separate the X variable, the features
x = clean_data.drop(columns=['age'])

In [4]:
# Review the y variable Series
print(y.head())
print(y.value_counts())

0    48
1     7
2    62
3    48
4    51
Name: age, dtype: int64
age
60    19
65    17
51    14
48    12
55    12
      ..
83     1
27     1
14     1
81     1
79     1
Name: count, Length: 76, dtype: int64


In [5]:
# Review the X variable DataFrame
print(x.head())
print(x.value_counts())

   Unnamed: 0  blood_pressure  specific_gravity  albumin  sugar  \
0           0              80             1.020      1.0    0.0   
1           1              50             1.020      4.0    0.0   
2           2              80             1.010      2.0    3.0   
3           3              70             1.005      4.0    0.0   
4           4              80             1.010      2.0    0.0   

   red_blood_cells  pus_cell  pus_cell_clumps  bacteria  blood_glucose_random  \
0                0         1                1         1            121.000000   
1                0         1                1         1            148.036517   
2                1         1                1         1            423.000000   
3                1         2                2         1            117.000000   
4                1         1                1         1            106.000000   

   ...  packed_cell_volume  white_blood_cell_count  red_blood_cell_count  \
0  ...                  44        

In [6]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

In [7]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state=1)

# Fit the model using training data
model.fit(x_train, y_train)

c:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [8]:
# Make a prediction using the testing data
predictions = model.predict(x_test)

In [9]:
# Generate a confusion matrix for the model
conf_matrix = confusion_matrix(y_test, predictions)
print(conf_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
# Print the classification report for the model
class_report = classification_report(y_test, predictions)
print("\nClassification Report:")
print(class_report)


Classification Report:
              precision    recall  f1-score   support

           8       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         2
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00         0
          25       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         2
          29       0.00      0.00      0.00         1
          30       0.00      0.00      0.00         0
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         2
          34       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         1
          39       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         1
   

c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\User\anaconda3\Lib\site-packages\sklearn\metrics\_classif